```{r introsetup, include=FALSE, eval=T}
rm(list = ls()) ; invisible(gc()) ; set.seed(42)
library(knitr)
library(tidyverse)
ggplot2::theme_set(bayesplot::theme_default())
opts_chunk$set(
  echo = T, message = F, warning = F, fig.height = 6, fig.width = 8,
  cache = T, cache.lazy = F, eval=T)
```

# Introduction {-}

Repository to develop descriptors of the environment and performance of tropical tree species in Paracou for the Camille and Sebastien analyses.

## Species

```{r introsp}
species <- readxl::read_xlsx("data/Species_list.xlsx")
kable(species, caption = "Studied species")
```


## Individuals

```{r introparacou, eval=F}
guyafor <- DBI::dbConnect(RSQLite::SQLite(), dbname = "data/guyafor.sql")
trees <- tbl(guyafor, "inventory") %>% 
  filter(Forest == "Paracou") %>% 
  filter(paste(Genus, Species) %in% local(species$Species)) %>% 
  collect() %>% 
  mutate(DBH = CircCorr/pi)
DBI::dbDisconnect(guyafor) ; rm(guyafor)
vroom::vroom_write(trees, "data/paracou.tsv")
```

```{r introparacoutab}
vroom::vroom("data/paracou.tsv", show_col_types = F) %>% 
  group_by(Genus, Species) %>% 
  summarise(N = n()) %>% 
  kable(caption = "Number of individuals per species")
```
