project:
  type: book
  output-dir: docs

book:
  title: "Tree Species Descriptors"
  author: "Sylvain Schmitt"
  date: last-modified
  chapters:
    - index.qmd
    - 1_env.qmd
    - 2_perf.qmd
    - 3_tests.qmd
  appendices:
    - 9_refs.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true
    number-depth: -1

editor: visual
